-- 50 Fantasy LEGO Sets seed data
-- Categories: Festninger og borger, Romfart og galakser, Hav og undervannsverdener, Skog og naturmagi, Fabeldyr og drager

INSERT INTO products (id, name, description, price, category, image_url, stock, piece_count, age_min) VALUES
-- Festninger og borger (IDs 1-10)
(1, 'Riddernes Bastion', 'A compact but mighty fortress guarded by brave knights in shining armor. Includes a drawbridge, tower with lookout, and two knight minifigures.', 249, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Riddernes+Bastion', 100, 287, 7),
(2, 'Borgmesterens Tårn', 'The grand tower of the city mayor, overlooking the kingdom from its highest spire. Features a spiral staircase, treasure room, and a rotating top floor.', 399, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Borgmesterens+T%C3%A5rn', 100, 412, 8),
(3, 'Elvenes Vaktpost', 'A riverside watchtower where brave soldiers keep watch over the kingdom''s borders. Comes with a small dock, supply boat, and three guard minifigures.', 499, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Elvenes+Vaktpost', 100, 578, 8),
(4, 'Drakeborgfestningen', 'A legendary dragon-themed fortress with sweeping battlements and a fire-breathing dragon statue at its gate. Includes a catapult, dungeon cell, and four minifigures.', 699, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Drakeborg', 100, 834, 9),
(5, 'Kongens Ridderborg', 'The royal castle of the noble king, surrounded by tall stone walls and flying banners. Features a throne room, armory, stable, and six minifigures including the king and queen.', 899, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Kongens+Borg', 100, 1092, 9),
(6, 'Trollmannens Tårn', 'A mysterious wizard''s tower filled with magical artifacts and bubbling potions. Includes a secret library, enchanted laboratory, and transformation chamber.', 1099, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Trollmannens+T%C3%A5rn', 100, 1387, 10),
(7, 'Drakejegernes Festning', 'An imposing fortress built by the legendary dragon hunters to protect the realm. Features multiple towers, a great hall, siege weapons, and eight detailed minifigures.', 1399, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Drakejegerne', 100, 1845, 10),
(8, 'Isrikets Slott', 'A magnificent ice castle ruled by an ancient snow queen. Built from translucent blue bricks, it features a frozen throne room, ice bridge, and magical prison tower.', 1699, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Isrikets+Slott', 100, 2234, 12),
(9, 'Det Store Kongeriket', 'The ultimate royal kingdom set spanning an entire hilltop. Includes castle keep, chapel, market square, blacksmith forge, and twelve minifigures with unique accessories.', 1999, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Kongeriket', 100, 2867, 12),
(10, 'Den Legendariske Borgherren', 'The most legendary castle ever constructed — a multi-tower masterpiece with a working portcullis, secret passages, fully furnished great hall, and sixteen highly detailed minifigures.', 2499, 'Festninger og borger', 'https://placehold.co/400x300/4a4e69/white?text=Borgherren', 100, 3612, 14),

-- Romfart og galakser (IDs 11-20)
(11, 'Månebisen Alfa', 'A small but powerful lunar rover designed to explore the surface of the moon. Easy to build and perfect for young space explorers, includes one astronaut minifigure.', 149, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=M%C3%A5nebisen+Alfa', 100, 148, 6),
(12, 'Romstasjonen Sirius', 'A modular space station orbiting a distant planet. Features a command module, science lab, solar panels, and a docking bay with escape pod.', 299, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Romstasjonen', 100, 312, 7),
(13, 'Galakseskipet Polaris', 'A sleek interstellar cruiser built for long voyages through the cosmos. Includes folding wings, hyperdrive engine, crew quarters, and two pilot minifigures.', 499, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Polaris', 100, 567, 8),
(14, 'Asteroidebasen Kappa', 'A mining base carved into a massive asteroid, harvesting rare crystals from the rock. Features drilling machinery, storage vaults, cargo shuttle, and four worker minifigures.', 699, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Asteroidebase', 100, 823, 9),
(15, 'Stjerneskytteren X-7', 'A lightning-fast fighter craft designed for space combat and interplanetary patrol missions. Has rotating laser cannons, cockpit ejector seat, and detailed wing mechanics.', 899, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Stjerneskytteren', 100, 1023, 9),
(16, 'Orions Romfartøy', 'A massive exploration vessel sent to the edge of the known universe. Features multiple decks, a xenobiology lab, holographic bridge, and six crew minifigures.', 1099, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Orion', 100, 1356, 10),
(17, 'Planetforskeren Nebula', 'A scientific research ship studying newly discovered planets on the galaxy''s rim. Includes detachable planetary lander, research drones, and eight scientist minifigures.', 1399, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Nebula', 100, 1734, 10),
(18, 'Galaksestasjonen Orion-7', 'A colossal deep-space station serving as a hub for interplanetary travel and trade. Features a rotating habitat ring, docking ports for five ships, and ten minifigures.', 1699, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Orion-7', 100, 2187, 12),
(19, 'Svart Hull Utforskeren', 'A reinforced science vessel built to study phenomena near black holes. Has shielded hull panels that open to reveal research instruments and a gravity measurement array.', 1999, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Svart+Hull', 100, 2645, 12),
(20, 'Galaksekeiserens Fartøy', 'The legendary flagship of the Galactic Emperor — a colossal warship bristling with weapons and housing an entire space armada within its hangar bays.', 2999, 'Romfart og galakser', 'https://placehold.co/400x300/1a1a2e/white?text=Keiserens+Fart%C3%B8y', 100, 4123, 14),

-- Hav og undervannsverdener (IDs 21-30)
(21, 'Dypdykkers Mini-Base', 'A tiny underwater research station perfect for beginner ocean explorers. Includes a small submarine, two divers, and a treasure chest with golden pieces.', 179, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Dypdykker', 100, 198, 6),
(22, 'Korallrevets Utpost', 'A colorful outpost nestled among coral reefs, home to marine scientists studying ocean life. Features a moonpool for divers, specimen tanks, and three minifigures.', 299, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Korallrevet', 100, 334, 7),
(23, 'Havbunnens Skattekiste', 'An ancient sunken ship resting on the ocean floor, filled with undiscovered treasures. Includes a shipwreck hull, diving bell, treasure trove, and ghost pirate minifigure.', 449, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Skattekiste', 100, 487, 8),
(24, 'Blekksprutkongens Borg', 'The underwater fortress of the mighty Kraken King, guarded by giant mechanical tentacles. Features a throne of coral, creature stables, and four sea warrior minifigures.', 649, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Blekksprutkong', 100, 745, 9),
(25, 'Havfruens Grotte', 'A magical underwater grotto where mermaids gather to sing and keep their secrets. Built with translucent bricks to represent crystal-clear water, includes mermaid figures.', 799, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Havfruens+Grotte', 100, 934, 8),
(26, 'Undervannsstasjonen Delta', 'A high-tech underwater research station studying deep ocean ecosystems. Modular design allows multiple configurations, includes submarine dock and five researcher minifigures.', 999, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Stasjon+Delta', 100, 1234, 10),
(27, 'Sjøhestens Palass', 'The grand palace of the noble Sea-Horse King, built from shells and sea glass. Features a coral throne room, garden of anemones, and royal guard of seahorse knights.', 1199, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Sj%C3%B8hestens+Palass', 100, 1567, 10),
(28, 'Atlantis Ekspedisjonen', 'The legendary lost city of Atlantis, finally discovered by a team of brave explorers. Massive set featuring sunken temples, ancient machinery, and twelve expedition minifigures.', 1499, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Atlantis', 100, 1945, 12),
(29, 'Dyphavets Hemmeligheter', 'A research mission to the deepest ocean trench uncovers alien-like creatures and luminescent landscapes. Features bioluminescent elements and deep-sea submersible craft.', 1699, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Dyphavet', 100, 2234, 12),
(30, 'Havfruenes Tempel', 'The sacred temple where the merfolk have worshipped the ocean gods since ancient times. A towering centerpiece set with detailed carvings, ritual chambers, and mythical sea creatures.', 1999, 'Hav og undervannsverdener', 'https://placehold.co/400x300/0077b6/white?text=Havfruenes+Tempel', 100, 2789, 14),

-- Skog og naturmagi (IDs 31-40)
(31, 'Alvefolkets Mini-Hytte', 'A cozy little woodland cottage where the forest elves make their home among the roots of an ancient oak. Perfect starter set for young builders, includes two elf minifigures.', 129, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Alve+Hytte', 100, 134, 6),
(32, 'Skogens Vaktpost', 'A treetop watchtower where elven rangers keep watch over the forest. Features a rope ladder, bow and arrow accessories, and a messenger owl companion.', 249, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Vaktpost', 100, 267, 7),
(33, 'Elvenes Bro', 'A mossy stone bridge spanning a magical forest stream, guarded by friendly trolls. Includes flowing water elements, lanterns, and troll bridge-keeper minifigure.', 349, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Elvenes+Bro', 100, 389, 7),
(34, 'Trollenes Skjulested', 'A hidden forest den where mischievous trolls hoard their collected treasures. Features a mushroom-topped hideout, trap door, secret stash, and three troll minifigures.', 499, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Trollenes', 100, 567, 8),
(35, 'Druiders Hellige Tre', 'The ancient sacred tree where forest druids perform their magical rituals at full moon. Features opening trunk with hidden chamber, mystical altar, and four druid minifigures.', 699, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Hellige+Tre', 100, 823, 9),
(36, 'Feen Glorias Hage', 'The enchanted garden of the fairy queen, blooming with magical flowers that glow at night. Features transforming flowers, butterfly companions, and fairy minifigures with wings.', 899, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Glorias+Hage', 100, 1087, 8),
(37, 'Skogens Hemmelige Sti', 'A winding secret path through the magical forest, alive with hidden creatures and ancient waymarkers. Features branching paths, hidden doors in tree trunks, and forest spirit figures.', 1099, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Hemmelig+Sti', 100, 1356, 9),
(38, 'Alvedronningens Borg', 'The grand forest castle of the Elven Queen, grown from living wood and adorned with flowers. Features a great tree-trunk throne room, hanging gardens, and eight royal elf minifigures.', 1299, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Alvedronning', 100, 1678, 10),
(39, 'Naturmagens Tempel', 'An ancient stone temple deep in the primeval forest, where nature magic and earth power converge. Features crumbling ruins, vines, magical artifacts, and mysterious guardians.', 1399, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Naturmagens+Tempel', 100, 2012, 12),
(40, 'Den Magiske Eikeskogen', 'The ultimate magical forest set — an entire enchanted ecosystem complete with a great oak village, underground gnome tunnels, treehouse community, and sixteen minifigures.', 1499, 'Skog og naturmagi', 'https://placehold.co/400x300/2d6a4f/white?text=Eikeskogen', 100, 2234, 12),

-- Fabeldyr og drager (IDs 41-50)
(41, 'Ildormens Unge', 'A small but feisty young fire dragon just learning to breathe fire. Poseable wings and jaw, includes a young dragon trainer minifigure with fireproof suit.', 299, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Ildormen+Unge', 100, 312, 7),
(42, 'Grifonen Silverklør', 'A majestic silver-clawed griffin — half eagle, half lion — perched on its mountain nest. Features poseable wings, articulated talons, and includes a royal rider minifigure.', 499, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Grifonen', 100, 534, 8),
(43, 'Dragehvalpen Eldur', 'An adorable dragon puppy named Eldur who breathes harmless sparks and loves to play. Includes interactive elements, toy accessories, and a child dragon keeper minifigure.', 699, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Dragehvalpen', 100, 767, 7),
(44, 'Einhornens Lysheim', 'The magical home of a celestial unicorn in the clouds, built from pearlescent white and gold bricks. Features rainbow bridge, starlight chamber, and three unicorn caretaker minifigures.', 899, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Einhornens', 100, 1023, 8),
(45, 'Fenriksulvens Tilholdssted', 'The volcanic lair of the mighty Fenrix wolf, a creature of fire and shadow. Features lava pools, shadow-crystal formations, and wolf-rider warrior minifigures.', 1099, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Fenriksulv', 100, 1287, 10),
(46, 'Basiliskens Huler', 'The labyrinthine cave complex of a stone-gazing basilisk serpent. Includes winding tunnels, petrified explorers (statues), and brave adventurer minifigures with mirror shields.', 1299, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Basiliskens', 100, 1567, 10),
(47, 'Dragedronningens Eggehule', 'A volcanic egg chamber where the Dragon Queen tends to her precious clutch of dragon eggs. Features hatching egg mechanics, temperature-color-changing bricks, and guard dragon minifigures.', 1599, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Eggehule', 100, 1934, 12),
(48, 'Fønixfuglens Reir', 'The magnificent nest of the immortal phoenix, rebuilt from its own ashes atop a volcano. Features flame-colored bricks, rising and falling phoenix mechanics, and five myth-keeper minifigures.', 1999, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=F%C3%B8nixfuglen', 100, 2456, 12),
(49, 'Ormgardenes Festning', 'The fortress of the Dragon Guard, sworn protectors of the world''s last dragon eggs. Epic multi-tower fortress with wyrm decorations, hatchery, and twelve armored guardian minifigures.', 2399, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Ormgardene', 100, 3123, 14),
(50, 'Dragedronningens Rede', 'The ultimate dragon set — the mountain stronghold of the legendary Dragon Queen herself. A monumental build featuring a fully poseable giant dragon, volcanic mountain, and sixteen minifigures.', 2799, 'Fabeldyr og drager', 'https://placehold.co/400x300/6d2b7c/white?text=Dragedronning', 100, 4567, 14);
